### ISSUE TITLE
Excellent work! Will the code be released?

### ISSUE THREAD

**Issue by StellarOdys2ey** [neuroexplicit-saar/Discover-then-Name#1]

**Comment by Jai2500** [comment]
Dear Authors, 

Congratulations on your work! Looking forward to the code being released at the earliest.

Thanks,

**Comment by sukrutrao** [comment]
@StellarOdys2ey @Jai2500 We have uploaded code for the primary components of our work. We will also upload visualisation code and other auxiliary scripts in the coming days. Sorry for the delay.

**Comment by sukrutrao** [comment]
@StellarOdys2ey @Jai2500 We have now also uploaded the visualisation code.
