### ISSUE TITLE
waiting for code to be released

### ISSUE THREAD

**Issue by hiteshhedwig** [neuroexplicit-saar/Discover-then-Name#2]
Dear authors,

please release the code. looking forward to understand the paper in depth.

Thank you

**Comment by sukrutrao** [comment]
@hiteshhedwig We have uploaded code for the primary components of our work. We will also upload visualisation code and other auxiliary scripts in the coming days. Sorry for the delay.

**Comment by sukrutrao** [comment]
@hiteshhedwig We have now also uploaded the visualisation code.
