### ISSUE TITLE
pretrained SAE models

### ISSUE THREAD

**Issue by krishnakanthnakkav2** [neuroexplicit-saar/Discover-then-Name#4]
Dear @sukrutrao @SwetaMahajan 

Thank you for sharing the code. Would you mind sharing the weights of SAE and also the concept names associated to each neuron.

Thank you.

**Comment by heetez1euler** [comment]
@sukrutrao @SwetaMahajan  +1 for this

**Comment by sukrutrao** [comment]
Hi @KKNakkav2, @heetez1euler, we will upload these soon.

**Comment by KKNakkav2** [comment]
Thank you.

**Comment by krishnakanthnakkav2** [comment]
Hello authors,

Any update on this.

**Comment by SwetaMahajan** [comment]
Hi @krishnakanthnakkav2, please find the checkpoints and the assigned names at the following link: 
https://nextcloud.mpi-klsb.mpg.de/index.php/s/PZYoKSq29XaEgL6

**Comment by krishnakanthnakkav2** [comment]
Thank you for releasing!
